version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: sunday
      time: "03:00"
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/docs/"
    schedule:
      interval: monthly
      day: sunday
      time: "03:00"
    versioning-strategy: increase
