version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    groups:
      dev-dependencies:
        patterns:
            - "eslint"
            - "stylelint"
            - "prettier"
            - "postcss"
    open-pull-requests-limit: 10
    versioning-strategy: increase
